spring:
  datasource:
    url: jdbc:h2:tcp:localhost/~/spring-jpa-ch-01
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    database: h2
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug